name: test

on:
  pull_request:
  push:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.2
          elixir-version: 1.13.4

      - name: Test
        run: |
          mix deps.get
          mix coveralls.github
